sudo: required
dist: trusty
before_install:
   - sudo apt-get update
install:
   - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk

script:
   - latexmk -pdf main.tex
notifications:
  slack: kks32:vsrIj5wVAmBbEQDpldE2GxcH
