sudo: required
dist: trusty
before_install:
   - sudo add-apt-repository ppa:jonathonf/texlive -y
   - sudo apt-get update
install:
   - sudo apt install texlive-full

script:
   - latexmk -pdf main.tex
notifications:
  slack: kks32:vsrIj5wVAmBbEQDpldE2GxcH
